### ISSUE TITLE
Part 2 Scores

### ISSUE THREAD

**Issue by AbdulAli** [CMPUT301F22T06/CMPUT301F22T06_team_project#97]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/abdulalib/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | score   (/3) | comment | Final   comments
-- | -- | -- | -- | -- | -- | -- | -- | --
Tool Practices | Product   Backlog | Object-Oriented   Analysis | User   Interface Mockup and Storyboard | Other
3 | Please   divide work properly, it seems like only two people pushed the stories and   that is the reason that risk levels, story points, and UStory details are   missing from the project cards. start using branches for each issue. | 2 | Story   points missing risk points missing, user stories acceptance criteria missing. | 2 | •   Clear, readable, consistent, and organized: yes     • Covers key classes: see comments     • Complete responsibilities: see comments     • Complete collaborators: see comments     • Object-oriented: Yes.      • Cohesive classes: Yes     • Coupling managed: Yes          Some of the key class are missing for example, in the current version I   cannot see Ingredient Storage which contain list of ingredients and will be   used as a collaborators in the recipe class. Similarly I cannot see recipe   list which will contain list of recipes and will be used in the meal plan as   a collaborator. | 3 | Unrealistic   data in the sotryboards. The overall wireframe could have been better with   some colors, if more people had contributed to this wireframe. | Please   fix all the problems before Part-3. More team members need to contribute. It   seems like 3-4 people worked in total.

</body>

</html>

**Comment by AbdulAli** [comment]
Hi guys @dheadrick1618 @Saheel-Sarker @Gentoxic @shaboi777 
Please find your other team members and get them to sign up for this repository :) 
For the feedback, please create a separate issues with tag: `Addressing Feedback`, and fix them before Part-3.

**Comment by dheadrick1618** [comment]
Not sure what you mean. All six team members are listed as contributors in this repo.  (see : )
![image](https://user-images.githubusercontent.com/28939664/199370982-e33b8564-297a-4d98-9486-46112844188e.png)

**Comment by dheadrick1618** [comment]
Unsure what is meant by; " user story risk points are missing " We have both a weighting and a risk level associated with each issue. A few new issues are missing but any involving the original planning and user story / requirements. This was completed in our first team meeting of this semester. (see our project page with associated organized tabs) 
![image](https://user-images.githubusercontent.com/28939664/199371683-91f98816-c0a1-40f4-8a36-e2dd5b0a9422.png)

**Comment by dheadrick1618** [comment]
@AbdulAli We are seriously in need of a meeting concerning all of these things. Also concerning the email you just sent out about categories and locations being dynamic instead of hardcoded:: You have insisted that we make things like the ingredient and location models abstract, so that we may create child classes which extended them. With this new information if they are expected to be dynamic and selected by the user, we will have to essentially undo a few days worth of work and fundamentally change our approach.

**Comment by AbdulAli** [comment]
Hi @dheadrick1618 , yes. Unfortunately Ken is firm on these classes not being abstract.
That means we are not doing OOP anymore and just adding strings being thrown in by the users. 
If it troubles you too much, at this point, then you can submit what you want but make sure to fix things by next iteration i.e. Part-4. Thanks!

**Comment by dheadrick1618** [comment]
That is fine I just refactored our code to use a singleton class which contains an array for these user defined attributes now.
